apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-pw-app
  labels:
    app: python-pw-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-pw-app
  template:
    metadata:
      labels:
        app: python-pw-app
    spec:
      imagePullSecrets:
        - name: regcred   # if pulling from private Docker Hub
      containers:
        - name: python-pw-app
          image: prem24/python-pw-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: pw-storage
              mountPath: /app/data
      volumes:
        - name: pw-storage
          emptyDir: {}