apiVersion: v1
kind: Service
metadata:
  name: python-pw-app-service
  labels:
    app: python-pw-app
spec:
  selector:
    app: python-pw-app   # must match Deployment labels
  ports:
    - protocol: TCP
      port: 80           # service port (inside cluster)
      targetPort: 5000   # container port
  type: NodePort        # host expose service