name: Python Build
# Tags
#1. echo "BUILD_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
#   example tag: 20260819080237
#
#2. echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
#   example: b6a8884
#
#3. echo "TAG=${GITHUB_REF_NAME}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
#   example: feature-task1-20260819095649



permissions:
  contents: read
  packages: write
  deployments: write

on:
  push:
   branches: [ feature-task1 ]

  workflow_dispatch:
    inputs:
      environment: 
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:  
          - dev
          - stage
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

       # Detect changes in src/ or requirements.txt or Dockerfile
      - name: Detect code changes
        id: changes
        run: |
          if git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- src requirements.txt Dockerfile; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi
          
      - name: Set Up Python
        if: env.changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install Dependencies
        if: env.changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        if: env.changed == 'true'
        run: pytest || echo "No tests found, skipping..."
      
      - name: Set Build Tag
        if: env.changed == 'true'
        run: |
          echo "TAG=${GITHUB_REF_NAME}-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      
      - name: Docker Build
        if: env.changed == 'true'
        run: |
          docker build -t python-pw-app .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          #username: ${{ secrets.DOCKER_USERNAME }}
          username: prem24
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # If no changes, just show last image tag
      - name: Show last Image Tag
        if: env.changed == 'false'
        run: |
          echo "No changes in src/ folder."
          echo "Last pushed image tag:"
          docker pull prem24/python-pw-app:latest
          docker images prem24/python-pw-app --format "{{.Repository}}:{{.Tag}}" | head -n 1

      - name: Docker Push
        if: env.changed == 'true'
        run: |
          docker tag python-pw-app:latest prem24/python-pw-app:latest
          docker push prem24/python-pw-app:latest
          docker tag python-pw-app:latest prem24/python-pw-app:$TAG
          docker push prem24/python-pw-app:$TAG
